import React, { useCallback, useEffect, useMemo, useState } from 'react';

import { api, errorMessage } from '../config';
import { useStreamingGeneration } from '../hooks/useStreamingGeneration';
import GenerationProgress from './generator/GenerationProgress';
import GeneratorForm from './generator/GeneratorForm';
import TrackReviewList from './generator/TrackReviewList';

/**
 * Playlist generation, as a small state machine:
 *   form -> generating -> review -> creating -> created
 *
 * Previously one 800-line component holding thirteen useState hooks, the SSE
 * parsing, a duplicate non-streaming code path and three screens.
 */
export default function PlaylistGenerator({ onTokenExpired }) {
  const [query, setQuery] = useState('');
  const [trackCount, setTrackCount] = useState(10);
  const [selectedIds, setSelectedIds] = useState(() => new Set());
  const [creating, setCreating] = useState(false);
  const [createError, setCreateError] = useState(null);
  const [created, setCreated] = useState(null);

  const generation = useStreamingGeneration();
  const { status, playlist, error, generate, cancel, reset } = generation;

  // Every track starts selected once a playlist arrives.
  useEffect(() => {
    if (playlist?.tracks) {
      setSelectedIds(new Set(playlist.tracks.map((t) => t.spotify_id)));
    }
  }, [playlist]);

  // An expired session during generation should send the user back to login,
  // not just show a message.
  useEffect(() => {
    if (error?.isAuthError) onTokenExpired?.();
  }, [error, onTokenExpired]);

  const toggleTrack = useCallback((spotifyId) => {
    setSelectedIds((prev) => {
      const next = new Set(prev);
      if (next.has(spotifyId)) next.delete(spotifyId);
      else next.add(spotifyId);
      return next;
    });
  }, []);

  const selectedTracks = useMemo(
    () => (playlist?.tracks ?? []).filter((t) => selectedIds.has(t.spotify_id)),
    [playlist, selectedIds],
  );

  const startOver = () => {
    reset();
    setSelectedIds(new Set());
    setCreated(null);
    setCreateError(null);
  };

  const handleCreate = async () => {
    if (selectedTracks.length === 0) return;
    setCreating(true);
    setCreateError(null);

    try {
      const { data } = await api.post('/api/create-playlist', {
        name: playlist.playlist_name,
        track_ids: selectedTracks.map((t) => t.spotify_id),
        description: `Generated by Aelyra for: "${query}"`,
      });
      setCreated(data);
    } catch (err) {
      if (err.response?.status === 401) {
        onTokenExpired?.();
        return;
      }
      setCreateError(errorMessage(err, 'Could not create the playlist on Spotify.'));
    } finally {
      setCreating(false);
    }
  };

  // --- created ------------------------------------------------------------
  if (created) {
    return (
      <div className="card">
        <div className="success" role="status">
          <h2 style={{ marginBottom: 8 }}>Playlist created</h2>
          <p>
            &ldquo;{playlist.playlist_name}&rdquo; is in your Spotify account with{' '}
            {selectedTracks.length} {selectedTracks.length === 1 ? 'track' : 'tracks'}.
          </p>
        </div>
        <div className="btn-row">
          {/* The old success screen told users to go and find it themselves. */}
          {created.playlist_url && (
            <a
              className="btn"
              href={created.playlist_url}
              target="_blank"
              rel="noopener noreferrer"
              style={{ display: 'inline-block', textDecoration: 'none' }}
            >
              Open in Spotify
            </a>
          )}
          <button type="button" className="btn btn-secondary" onClick={startOver}>
            Create another
          </button>
        </div>
      </div>
    );
  }

  // --- creating -----------------------------------------------------------
  if (creating) {
    return (
      <div className="card">
        <div className="loading">
          <h3>Saving to Spotify…</h3>
          <p>Adding {selectedTracks.length} tracks to your account.</p>
        </div>
      </div>
    );
  }

  // --- generating ---------------------------------------------------------
  if (status === 'streaming') {
    return (
      <GenerationProgress
        passProgress={generation.passProgress}
        currentPass={generation.currentPass}
        statusMessage={generation.statusMessage}
        foundTracks={generation.foundTracks}
        onCancel={cancel}
      />
    );
  }

  // --- review -------------------------------------------------------------
  if (status === 'done' && playlist) {
    // A zero-track result used to render a completely blank screen.
    if (!playlist.tracks || playlist.tracks.length === 0) {
      return (
        <div className="card">
          <div className="empty-state">
            <h3>No tracks found</h3>
            <p>
              Nothing matching that request could be found on Spotify. Try
              describing the mood or genre differently.
            </p>
            <div className="btn-row" style={{ justifyContent: 'center', marginTop: 20 }}>
              <button type="button" className="btn" onClick={startOver}>
                Try another description
              </button>
            </div>
          </div>
        </div>
      );
    }

    return (
      <div className="card">
        <h2 style={{ marginBottom: 4 }}>{playlist.playlist_name}</h2>
        <p className="text-muted" style={{ marginBottom: 16 }}>
          Pick the tracks you want, then save them to Spotify.
        </p>

        {generation.partial && (
          <div className="warning" role="status">
            {generation.partial.message}
          </div>
        )}

        {createError && (
          <div className="error" role="alert">
            {createError}
          </div>
        )}

        <TrackReviewList
          tracks={playlist.tracks}
          selectedIds={selectedIds}
          onToggle={toggleTrack}
          onSelectAll={() => setSelectedIds(new Set(playlist.tracks.map((t) => t.spotify_id)))}
          onDeselectAll={() => setSelectedIds(new Set())}
        />

        <div className="btn-row" style={{ marginTop: 20 }}>
          <button
            type="button"
            className="btn"
            onClick={handleCreate}
            disabled={selectedTracks.length === 0}
          >
            Save {selectedTracks.length} {selectedTracks.length === 1 ? 'track' : 'tracks'} to Spotify
          </button>
          <button type="button" className="btn btn-secondary" onClick={startOver}>
            Start over
          </button>
        </div>
      </div>
    );
  }

  // --- form (with any previous failure shown) -----------------------------
  return (
    <>
      {status === 'error' && error && !error.isAuthError && (
        <div className="error" role="alert">
          <strong>Generation failed.</strong> {error.message}
        </div>
      )}
      <GeneratorForm
        query={query}
        onQueryChange={setQuery}
        trackCount={trackCount}
        onTrackCountChange={setTrackCount}
        onSubmit={() => generate(query.trim(), trackCount)}
        disabled={status === 'streaming'}
      />
    </>
  );
}
