"""Tests for the Spotify request shaping that caused a live 400.

Spotify rejects an over-length playlist name or description with a bare 400 and
no indication of which field was at fault, so the limits are enforced before the
request goes out.
"""

import httpx
import pytest

from app.services.spotify_service import SpotifyService


class TestClamp:
    def test_short_values_pass_through_untouched(self):
        assert SpotifyService._clamp("Cosmic Groove Currents", 100) == "Cosmic Groove Currents"

    def test_over_length_values_are_truncated_to_the_limit(self):
        clamped = SpotifyService._clamp("x" * 500, 300)
        assert len(clamped) == 300
        assert clamped.endswith("…")

    def test_none_becomes_an_empty_string(self):
        assert SpotifyService._clamp(None, 300) == ""


class TestCreatePlaylist:
    """The failure seen in production: a long query made the description, which
    embeds it, exceed Spotify's 300-character cap."""

    async def test_a_long_description_is_clamped_rather_than_rejected(self, monkeypatch):
        captured = {}

        async def fake_post(self, url, headers=None, json=None, timeout=None):
            captured.update(json)
            return httpx.Response(200, json={"id": "abc", "external_urls": {"spotify": "https://x"}},
                                  request=httpx.Request("POST", url))

        monkeypatch.setattr(httpx.AsyncClient, "post", fake_post)

        long_query = "chill indie folk " * 40  # ~680 characters
        service = SpotifyService("token")
        await service.create_playlist("A Name", f'Generated by Aelyra for: "{long_query}"')

        assert len(captured["description"]) <= SpotifyService.MAX_PLAYLIST_DESCRIPTION
        assert len(captured["name"]) <= SpotifyService.MAX_PLAYLIST_NAME

    async def test_an_empty_name_falls_back_rather_than_sending_nothing(self, monkeypatch):
        captured = {}

        async def fake_post(self, url, headers=None, json=None, timeout=None):
            captured.update(json)
            return httpx.Response(200, json={"id": "abc"}, request=httpx.Request("POST", url))

        monkeypatch.setattr(httpx.AsyncClient, "post", fake_post)

        await SpotifyService("token").create_playlist("   ", "desc")
        assert captured["name"] == "Aelyra Playlist"


class TestAddTracks:
    async def test_more_than_100_tracks_are_split_across_requests(self, monkeypatch):
        """Spotify accepts at most 100 uris per request, and M3U upload allows 500."""
        batches = []

        async def fake_post(self, url, headers=None, json=None, timeout=None):
            batches.append(len(json["uris"]))
            return httpx.Response(200, json={"snapshot_id": "s"}, request=httpx.Request("POST", url))

        monkeypatch.setattr(httpx.AsyncClient, "post", fake_post)

        await SpotifyService("token").add_tracks_to_playlist("pid", [f"t{i}" for i in range(250)])

        assert batches == [100, 100, 50]


class TestErrorPropagation:
    async def test_an_expired_token_surfaces_as_401_not_a_generic_failure(self, monkeypatch):
        """The router maps 401 to a re-login prompt, but only if the status
        code survives. It used to be wrapped in a plain Exception."""

        async def fake_get(self, url, headers=None, timeout=None, params=None):
            return httpx.Response(401, json={"error": {"message": "The access token expired"}},
                                  request=httpx.Request("GET", url))

        monkeypatch.setattr(httpx.AsyncClient, "get", fake_get)

        with pytest.raises(httpx.HTTPStatusError) as exc:
            await SpotifyService("expired").get_user_profile()

        assert exc.value.response.status_code == 401

    async def test_spotify_explanation_is_logged(self, monkeypatch, caplog):
        async def fake_post(self, url, headers=None, json=None, timeout=None):
            return httpx.Response(400, json={"error": {"message": "Invalid base62 id"}},
                                  request=httpx.Request("POST", url))

        monkeypatch.setattr(httpx.AsyncClient, "post", fake_post)

        with caplog.at_level("ERROR"):
            with pytest.raises(httpx.HTTPStatusError):
                await SpotifyService("token").create_playlist("name", "desc")

        assert "Invalid base62 id" in caplog.text
