"""Add playlist history and tracks tables

Revision ID: 8c3fb52190cb
Revises: 1d44e78f7caa
Create Date: 2025-06-25 08:15:29.922877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c3fb52190cb'
down_revision: Union[str, None] = '1d44e78f7caa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playlist_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('playlist_hash', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('playlist_name', sa.String(length=255), nullable=False),
    sa.Column('user_description', sa.Text(), nullable=True),
    sa.Column('spotify_playlist_id', sa.String(length=255), nullable=False),
    sa.Column('spotify_playlist_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('track_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_playlist_history_id'), 'playlist_history', ['id'], unique=False)
    op.create_index(op.f('ix_playlist_history_playlist_hash'), 'playlist_history', ['playlist_hash'], unique=True)
    op.create_table('playlist_tracks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('playlist_history_id', sa.Integer(), nullable=False),
    sa.Column('spotify_track_id', sa.String(length=255), nullable=False),
    sa.Column('track_name', sa.String(length=255), nullable=False),
    sa.Column('artist_name', sa.String(length=255), nullable=False),
    sa.Column('album_name', sa.String(length=255), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['playlist_history_id'], ['playlist_history.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_playlist_tracks_id'), 'playlist_tracks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_playlist_tracks_id'), table_name='playlist_tracks')
    op.drop_table('playlist_tracks')
    op.drop_index(op.f('ix_playlist_history_playlist_hash'), table_name='playlist_history')
    op.drop_index(op.f('ix_playlist_history_id'), table_name='playlist_history')
    op.drop_table('playlist_history')
    # ### end Alembic commands ###
